services:
  db:
    build: db
    hostname: msdb
    environment:
      - POSTGRES_USER=ms
      - POSTGRES_PASSWORD=mysecretpassword

  sparql:
    build: sparql
    depends_on:
      - db
    ports:
      - "8080:8080"
